In [2]:
import numpy as np

## 1. Creating arrays

#### 1-D Array

In [2]:
a = np.array([1,2,3])
a

array([1, 2, 3])

#### 2-D Array

In [3]:
b = np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

 #### 3-D Array

In [4]:
c = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
c

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

### 1a. Getting Dimmensions of array

In [5]:
a.ndim

1

In [6]:
b.ndim

2

In [7]:
c.ndim

3

### 1b. Getting shape of an Array

In [8]:
a.shape

(3,)

In [9]:
b.shape

(2, 3)

In [10]:
c.shape

(2, 2, 3)

### 1c. Getting datatype

In [11]:
a.dtype

dtype('int32')

In [12]:
a = np.array([1,2,3], dtype = 'int16')

In [13]:
a

array([1, 2, 3], dtype=int16)

In [15]:
# Getting Size

a.itemsize

2

### 1d. Getting Total Size of an Array

In [16]:
a.size * a.itemsize

6

In [17]:
# Simpler way

a.nbytes

6

## 2. Accessing/Updating elements of any array

In [18]:
x = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(x)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [21]:
x[1,2]

10

In [22]:
# Second row

x[1, :]

array([ 8,  9, 10, 11, 12, 13, 14])

In [23]:
# 3rd column

x[:, 2]

array([ 3, 10])

### 2a. Using stepsize

In [27]:
x[:, 0:7:2]            

array([[ 1,  3,  5,  7],
       [ 8, 10, 12, 14]])

In [28]:
x[:, 2:5:2]

array([[ 3,  5],
       [10, 12]])

### 2b. Updating elements

In [29]:
x

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [30]:
x[1,3] = 56

In [31]:
x

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 56, 12, 13, 14]])

In [33]:
# Changing all elements of column containing 3 to 72

x[:, 2] = 72
x

array([[ 1,  2, 72,  4,  5,  6,  7],
       [ 8,  9, 72, 56, 12, 13, 14]])

In [35]:
# Changing all elements of column containing 6, 13 to 32, 98

x[:, 5] = [32,98]
x

array([[ 1,  2, 72,  4,  5, 32,  7],
       [ 8,  9, 72, 56, 12, 98, 14]])

#### Things get a bit complicated in 3-D array (work outside in)

In [36]:
y = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [37]:
print(y)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [38]:
y.ndim

3

In [40]:
y[0,1,2]

6

In [41]:
y[1,1,1]

11

In [42]:
y

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [43]:
# Getting set of elements

y[:,1,:]

array([[ 4,  5,  6],
       [10, 11, 12]])

In [44]:
y[:,0,:]

array([[1, 2, 3],
       [7, 8, 9]])

In [45]:
y[:,:,1]

array([[ 2,  5],
       [ 8, 11]])

#### Changing elements in 3-D array

In [47]:
y

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [48]:
# First grab that portion

y[0,1,:]

array([4, 5, 6])

In [49]:
# Replace with same size dataset

y[0,1,:] = [11,12,13]

In [50]:
y

array([[[ 1,  2,  3],
        [11, 12, 13]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [52]:
y[0,:,2]

array([ 3, 13])

In [54]:
y[0,:,2] = [56,57]
y

array([[[ 1,  2, 56],
        [11, 12, 57]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [56]:
y[:,:,1]

array([[ 2, 12],
       [ 8, 11]])

In [58]:
y[:,:,1] = [1,2],[3,4]
y

array([[[ 1,  1, 56],
        [11,  2, 57]],

       [[ 7,  3,  9],
        [10,  4, 12]]])

## 3. Creating arrays with predefined presets

In [62]:
# All 0s matrix

zero = np.zeros((2,3,3))
zero

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [71]:
# All 1s matrix

np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [64]:
# Any other number

np.full((3,3), 10)

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [65]:
# If we want to use the shape of our any previous array to create a new array

x

array([[ 1,  2, 72,  4,  5, 32,  7],
       [ 8,  9, 72, 56, 12, 98, 14]])

In [66]:
# Suppose we want to use the above array and create a new array containig only 99s

np.full_like(x, 99)

array([[99, 99, 99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99, 99, 99]])

In [67]:
# Alternative way

np.full(x.shape,99)

array([[99, 99, 99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99, 99, 99]])

In [72]:
# Making a matrix with random numbers between 0 and 1

np.random.rand(2,3)

array([[0.13946443, 0.34283809, 0.20404692],
       [0.49850823, 0.62490004, 0.26978758]])

In [74]:
# We can also sample a predefined array size to make a new random array

np.random.random_sample(x.shape)

array([[0.7640261 , 0.40635119, 0.9801406 , 0.89911068, 0.32941859,
        0.5770602 , 0.71799804],
       [0.87519611, 0.55022289, 0.02333058, 0.15335068, 0.12074193,
        0.69916112, 0.27801542]])

In [76]:
# Making a random integer array

np.random.randint(1,6, size=(3,2))

array([[1, 4],
       [4, 1],
       [2, 3]])

In [77]:
# Identity Matrix (always square)

np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [79]:
# Repeat an array

arr = np.array([[1,2,3]])   # Making it intentionally 2-D to use axis parameter

rep = np.repeat(arr,2, axis=1)

rep

array([[1, 1, 2, 2, 3, 3]])

In [81]:
rep = np.repeat(arr,3, axis=0)
rep

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

## 4. Copying contents of an Array

### While copying the contents always use copy() function

In [3]:
# Suppose we hav an array

n = np.array([1,2,3])

In [4]:
# If we assign a new variable to a n as:

z = n
print(z)

[1 2 3]


In [5]:
# We think that we have made a copy successfully but here's the issue

z[0] = 21
print(n)

[21  2  3]


#### When we change any value in z it is also chnged in n by this method

### Using copy()

In [6]:
n = np.array([1,2,3])

In [7]:
z = n.copy()
print(z)

[1 2 3]


In [8]:
z[0] = 21
print(n)

[1 2 3]


In [9]:
print(z)

[21  2  3]


## 5. Mathematics in Numpy

### 5a. Element wise maths

In [10]:
n

array([1, 2, 3])

In [11]:
n + 2

array([3, 4, 5])

In [12]:
n/2

array([0.5, 1. , 1.5])

In [14]:
n

array([1, 2, 3])

In [13]:
n + z

array([22,  4,  6])

In [16]:
# Taking sin of all elements

np.sin(n)

array([0.84147098, 0.90929743, 0.14112001])

### 5b. Linear Algebra

In [19]:
a = np.full((2,3), 1)
print(a)

[[1 1 1]
 [1 1 1]]


In [20]:
b = np.full((3,4), 2)
print(b)

[[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]


In [23]:
# Multiplying Matrix a and b

np.matmul(a,b)

array([[6, 6, 6, 6],
       [6, 6, 6, 6]])

In [26]:
a = np.full((2,2), 2)
print(a)

[[2 2]
 [2 2]]


In [28]:
np.linalg.det(a)

0.0

### 5c. Simple Stats

In [29]:
stats = np.array([[1,2,3],[4,5,6]])
print(stats)

[[1 2 3]
 [4 5 6]]


In [30]:
# Min
np.min(stats)

1

In [31]:
# Max
np.max(stats)

6

In [32]:
# Axiswise max, min

np.min(stats, axis=0)

array([1, 2, 3])

In [33]:
np.max(stats, axis = 1)

array([3, 6])

In [34]:
# Sum
np.sum(stats)

21

In [35]:
# Axis wise Sum

np.sum(stats, axis=0)

array([5, 7, 9])

In [36]:
np.sum(stats, axis=1)

array([ 6, 15])

## 6. Reorganizing Arrays

### 6a. Changing Shape of the Array

In [37]:
before = np.array([[1,2,3],[4,5,6]])
print(before)

[[1 2 3]
 [4 5 6]]


In [43]:
after = before.reshape((6,1))
print(after)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [45]:
after = before.reshape((3,2))
print(after)

[[1 2]
 [3 4]
 [5 6]]


### 6b. Vertical/Horizontal Stack

In [46]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [47]:
b = np.array([3,4,5])
print(b)

[3 4 5]


In [48]:
# Vertical Stack

np.vstack([a,b,a,b,b])

array([[1, 2, 3],
       [3, 4, 5],
       [1, 2, 3],
       [3, 4, 5],
       [3, 4, 5]])

In [50]:
# Horizontal Stack

np.hstack([a,b,a])

array([1, 2, 3, 3, 4, 5, 1, 2, 3])

## 7. Miscellaneous 

### 7a. Loading a txt file with numbers directly into numpy

In [51]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata

array([[  1.,  13.,  21.,  11., 196.,  75.,   4.,   3.,  34.,   6.,   7.,
          8.,   0.,   1.,   2.,   3.,   4.,   5.],
       [  3.,  42.,  12.,  33., 766.,  75.,   4.,  55.,   6.,   4.,   3.,
          4.,   5.,   6.,   7.,   0.,  11.,  12.],
       [  1.,  22.,  33.,  11., 999.,  11.,   2.,   1.,  78.,   0.,   1.,
          2.,   9.,   8.,   7.,   1.,  76.,  88.]])

In [52]:
# But we see that all data is converted to float by default
# We can change that to integer as follows:

filedataint = filedata.astype('int32')
filedataint

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]])

### 7b. Boolean Masking and Advanced Indexing

In [53]:
## Boolean masking means checking an array on a certain parameter

filedataint > 100

# Checking the place where no. greater than 100 is present

array([[False, False, False, False,  True, False, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False, False,
        False, False, False, False, False, False, False, False, False]])

In [56]:
# Indexing on Boolean

filedataint[filedataint > 50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88])

In [61]:
filedataint

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]])

In [60]:
# Checking Boolean on Axis

np.any(filedataint > 100, axis = 0)

# Checking only in first row

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [62]:
np.any(filedataint > 100, axis=1)

array([ True,  True,  True])

In [63]:
np.all(filedataint > 100, axis=0)  

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [64]:
np.all(filedataint > 100, axis=1)

array([False, False, False])

In [65]:
# Multiple Conditions

((filedataint > 50) & (filedataint < 100))

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

### That's all. Keep Learning !!!

### For more resources: https://docs.scipy.org/doc/numpy-1.13.0/user/basics.html